#!/usr/bin/env bash
# =============================================================================
# RivrQuant EC2 Bootstrap Script
# Generated by Terraform templatefile() — do not edit on the instance directly.
# All ${...} tokens are Terraform substitutions; nginx/systemd $var references
# that lack curly braces are passed through unchanged.
# =============================================================================
set -euo pipefail

# Redirect all stdout/stderr to cloud-init log for post-boot debugging.
exec > >(tee /var/log/cloud-init-output.log | logger -t rivrquant-bootstrap) 2>&1

echo "=== RivrQuant Bootstrap started: $(date -u) ==="

# =============================================================================
# 1. System packages
# =============================================================================
dnf update -y
dnf install -y docker git nginx python3-pip curl jq

# =============================================================================
# 2. Docker Compose v2 (CLI plugin)
# =============================================================================
mkdir -p /usr/local/lib/docker/cli-plugins
curl -fsSL \
  "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

systemctl enable --now docker
usermod -aG docker ec2-user

echo "Docker $(docker --version) ready."
echo "Docker Compose $(docker compose version) ready."

# =============================================================================
# 3. Clone repository
# =============================================================================
git clone "${git_clone_url}" /opt/rivrquant
echo "Repository cloned to /opt/rivrquant."

# =============================================================================
# 4. Fetch secrets from AWS Secrets Manager → .env
# =============================================================================
SECRET_JSON=$(aws secretsmanager get-secret-value \
  --secret-id "${secret_arn}" \
  --region    "${aws_region}" \
  --query     SecretString \
  --output    text)

# Convert JSON object to KEY=VALUE lines, quoting values that contain spaces.
echo "$SECRET_JSON" | jq -r 'to_entries[] | .key + "=" + (.value | @sh)' \
  > /opt/rivrquant/.env

chmod 600 /opt/rivrquant/.env
echo ".env written with $(wc -l < /opt/rivrquant/.env) variables."

# =============================================================================
# 5. Build and start application containers
# =============================================================================
cd /opt/rivrquant

# Pass NEXT_PUBLIC_* as build args so the Next.js image is baked with them.
NEXT_PUBLIC_API_URL="${next_public_api_url}" \
NEXT_PUBLIC_SIGNALR_URL="${next_public_signalr_url}" \
  docker compose -f docker-compose.yml up --build -d

echo "Docker Compose stack started."

# =============================================================================
# 6. nginx — reverse proxy with WebSocket support for SignalR
# =============================================================================

%{ if domain_name != "" }
# --- HTTPS configuration with TLS termination ---

pip3 install --quiet certbot certbot-nginx

cat > /etc/nginx/conf.d/rivrquant.conf << 'NGINX_EOF'
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

# HTTP — serve ACME challenge, redirect everything else to HTTPS.
server {
    listen 80;
    server_name ${domain_name};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS
server {
    listen 443 ssl;
    server_name ${domain_name};

    ssl_certificate     /etc/letsencrypt/live/${domain_name}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${domain_name}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # Frontend (Next.js)
    location / {
        proxy_pass         http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection $connection_upgrade;
        proxy_set_header   Host       $host;
        proxy_set_header   X-Real-IP  $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    # .NET API
    location /api/ {
        proxy_pass         http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection $connection_upgrade;
        proxy_set_header   Host       $host;
        proxy_set_header   X-Real-IP  $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    # SignalR hubs (long-poll + WebSocket)
    location /hubs/ {
        proxy_pass         http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection $connection_upgrade;
        proxy_set_header   Host       $host;
        proxy_read_timeout 86400;
    }

    # Health check passthrough
    location /health {
        proxy_pass http://127.0.0.1:5000;
    }
}
NGINX_EOF

mkdir -p /var/www/certbot
systemctl enable --now nginx
nginx -t && nginx -s reload

# Attempt TLS certificate issuance. Fails gracefully if DNS hasn't propagated yet.
if certbot --nginx \
    -d "${domain_name}" \
    --non-interactive \
    --agree-tos \
    --email "${certbot_email}" \
    --redirect; then
  echo "TLS certificate issued successfully for ${domain_name}."
else
  echo "WARNING: certbot failed — DNS may not have propagated yet."
  echo "  Run manually: certbot --nginx -d ${domain_name} --email ${certbot_email}"
fi

%{ else }
# --- HTTP-only configuration (no domain / IP access) ---

cat > /etc/nginx/conf.d/rivrquant.conf << 'NGINX_EOF'
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    server_name _;

    # Frontend (Next.js)
    location / {
        proxy_pass         http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection $connection_upgrade;
        proxy_set_header   Host       $host;
        proxy_set_header   X-Real-IP  $remote_addr;
    }

    # .NET API
    location /api/ {
        proxy_pass         http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection $connection_upgrade;
        proxy_set_header   Host       $host;
        proxy_set_header   X-Real-IP  $remote_addr;
    }

    # SignalR hubs
    location /hubs/ {
        proxy_pass         http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection $connection_upgrade;
        proxy_set_header   Host       $host;
        proxy_read_timeout 86400;
    }

    # Health check
    location /health {
        proxy_pass http://127.0.0.1:5000;
    }
}
NGINX_EOF

systemctl enable --now nginx
nginx -t && nginx -s reload

%{ endif }

# =============================================================================
# 7. Systemd service — auto-start Docker Compose on reboot
# =============================================================================

cat > /etc/systemd/system/rivrquant.service << 'SYSTEMD_EOF'
[Unit]
Description=RivrQuant Application (Docker Compose)
After=docker.service network-online.target
Wants=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/opt/rivrquant
ExecStart=/usr/bin/docker compose -f /opt/rivrquant/docker-compose.yml up -d
ExecStop=/usr/bin/docker compose  -f /opt/rivrquant/docker-compose.yml down
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
SYSTEMD_EOF

systemctl daemon-reload
systemctl enable rivrquant.service

echo "=== RivrQuant Bootstrap complete: $(date -u) ==="
echo "Containers: $(docker compose -f /opt/rivrquant/docker-compose.yml ps --format 'table {{.Name}}\t{{.Status}}')"
